export const kolamVisualTokens = {
  fontFamily: 'Inter',
  colors: {
    bg: '#ffffff',
    fg: '#111827',
    primary: '#16a34a',
    primarySoft: '#e8f6ed',
    primaryFg: '#ffffff',
    secondary: '#e5e7eb',
    secondaryFg: '#111827',
    muted: '#f6f7f9',
    mutedSoft: '#fdfdfe',
    mutedFg: '#64748b',
    tableHeader: '#f2f3f5',
    border: '#e5e7eb',
    input: '#e2e8f0',
    navbar: '#f6f7f9',
    navbarFg: '#111827',
    mainSurface: '#ffffff',
    sidebar: '#fbfbfc',
    sidebarFg: '#111827',
    success: '#059669',
    successSoft: '#e6f4ec',
    warning: '#b7791f',
    warningSoft: '#fff7e6',
    danger: '#dc2626',
    dangerSoft: '#fce9e9',
    info: '#0ea5e9',
    infoSoft: '#eef7fb',
  },
  radius: {
    sm: 6,
    md: 7,
    lg: 8,
    xl: 10,
  },
  control: {
    inputHeight: 36,
    buttonSmHeight: 34,
    buttonMdHeight: 36,
    buttonPaddingX: 12,
    inputPaddingX: 12,
    badgePaddingX: 8,
    badgePaddingY: 2,
    badgeRadius: 999,
    fontSize: 13,
    badgeFontSize: 12,
  },
  surface: {
    cardChrome: {
      sourceSlot: 'card',
      radius: 8,
      background: 'bg',
      border: 'border',
      borderWidth: 1,
      shadow: 'shadow-xs',
      defaultSpacing: 24,
      compactSpacing: 16,
    },
    cardSlots: {
      sourceComponent:
        'E:\\Projects\\da-inventory-frontend\\src\\components\\ui\\card.tsx',
      card: {
        layout: 'flex-col',
        defaultSpacing: 24,
        compactSpacing: 16,
        paddingYUsesSpacing: true,
        hasTableOverflowHidden: true,
      },
      header: {
        layout: 'grid',
        rowGap: 4,
        paddingXUsesSpacing: true,
        actionPlacement: 'top-right',
      },
      title: {
        fontSize: 18,
        lineHeight: 24,
        compactFontSize: 16,
        fontWeight: 'semibold',
      },
      description: {
        fontSize: 14,
        color: 'mutedFg',
      },
      content: {
        paddingXUsesSpacing: true,
        tableBorderTop: true,
      },
      footer: {
        paddingXUsesSpacing: true,
        tablePaddingTopUsesSpacing: true,
      },
    },
    cardShadow: {
      sourceClass: 'shadow-xs',
      offsetY: 1,
      radius: 1,
      opacity: 0.04,
      elevation: 1,
    },
  },
  layout: {
    sidebarWidth: 272,
    sidebarDockWidth: 52,
    topNavHeight: 52,
    quickSearchHeight: 36,
    contentPadding: 16,
    cardSpacing: 24,
    cardCompactSpacing: 16,
    tableCellPaddingX: 20,
    tableCellPaddingY: 12,
    tableRowMinHeight: 52,
    navItemHeight: 36,
    navSectionGap: 24,
    navItemPaddingX: 8,
    dashboardRightRailWidth: 300,
    dashboardSectionGap: 24,
  },
} as const;

export type KolamVisualTokens = typeof kolamVisualTokens;
