import {useMemo} from 'react';
import type {KolamWorkspaceSurfaceProps} from '../components/kolam-workspace-surface';

type WorkspaceProps = KolamWorkspaceSurfaceProps;

export function useKolamWorkspaceController({
  activeModule,
  activeAmSurface,
  activeKolamSurface,
  activeNavigationItem,
  activeModuleRoute,
  activePluginRoute,
  cashflow,
  catalog,
  checkout,
  customer,
  dataset,
  plugins,
  onAmSurfaceSelect,
  onCommandSelect,
  onCustomerVisitConfirm,
  onDashboardRoute,
  onKolamSurfaceSelect,
  onModuleRouteSelect,
  onPluginRouteSelect,
  onSelectModule,
  onSalesGraphRangeSelect,
  sales,
  salesGraphRange,
  syncActivity,
}: WorkspaceProps) {
  const workspace = useMemo<WorkspaceProps>(
    () => ({
      activeModule,
      activeAmSurface,
      activeKolamSurface,
      activeNavigationItem,
      activeModuleRoute,
      activePluginRoute,
      cashflow,
      catalog,
      checkout,
      customer,
      dataset,
      plugins,
      onAmSurfaceSelect,
      onCommandSelect,
      onCustomerVisitConfirm,
      onDashboardRoute,
      onKolamSurfaceSelect,
      onModuleRouteSelect,
      onPluginRouteSelect,
      onSelectModule,
      onSalesGraphRangeSelect,
      sales,
      salesGraphRange,
      syncActivity,
    }),
    [
      activeModule,
      activeAmSurface,
      activeKolamSurface,
      activeNavigationItem,
      activeModuleRoute,
      activePluginRoute,
      cashflow,
      catalog,
      checkout,
      customer,
      dataset,
      plugins,
      onAmSurfaceSelect,
      onCommandSelect,
      onCustomerVisitConfirm,
      onDashboardRoute,
      onKolamSurfaceSelect,
      onModuleRouteSelect,
      onPluginRouteSelect,
      onSelectModule,
      onSalesGraphRangeSelect,
      sales,
      salesGraphRange,
      syncActivity,
    ],
  );

  return {workspace};
}
