import {StyleSheet} from 'react-native';
import {kolamVisualTokens as V} from '../domain/kolam-visual';

export const attentionPanelStyles = StyleSheet.create({
  attentionPanel: {
    position: 'absolute',
    top: V.layout.topNavHeight - 1,
    right: V.layout.contentPadding,
    zIndex: 20,
    width: 380,
    overflow: 'hidden',
    borderRadius: V.radius.lg,
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderWidth: 1,
  },
  attentionPanelHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: V.layout.cardCompactSpacing,
    paddingVertical: 10,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  attentionPanelTitle: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 14,
    fontWeight: '900',
  },
  attentionPanelDescription: {
    marginTop: 3,
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 11,
  },
  attentionPanelActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  attentionPanelUnread: {
    overflow: 'hidden',
    paddingHorizontal: V.control.badgePaddingX,
    paddingVertical: V.control.badgePaddingY,
    borderRadius: V.control.badgeRadius,
    color: V.colors.danger,
    backgroundColor: V.colors.warningSoft,
    fontFamily: V.fontFamily,
    fontSize: 11,
    fontWeight: '800',
  },
  attentionList: {
    maxHeight: 420,
  },
  attentionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: V.layout.cardCompactSpacing,
    paddingVertical: 12,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  attentionItemUnread: {
    backgroundColor: V.colors.successSoft,
  },
  attentionTone: {
    overflow: 'hidden',
    minWidth: 64,
    paddingHorizontal: V.control.badgePaddingX,
    paddingVertical: V.control.badgePaddingY,
    borderRadius: V.control.badgeRadius,
    color: V.colors.info,
    backgroundColor: V.colors.infoSoft,
    fontFamily: V.fontFamily,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  attentionToneSuccess: {
    color: V.colors.success,
    backgroundColor: V.colors.successSoft,
  },
  attentionToneWarning: {
    color: V.colors.warning,
    backgroundColor: V.colors.warningSoft,
  },
  attentionToneDanger: {
    color: V.colors.danger,
    backgroundColor: V.colors.warningSoft,
  },
  attentionItemCopy: {
    flex: 1,
    minWidth: 0,
  },
  attentionItemTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  attentionItemTitle: {
    flex: 1,
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    fontWeight: '900',
  },
  attentionUnreadDot: {
    marginTop: 5,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: V.colors.primary,
  },
  attentionItemMessage: {
    marginTop: 3,
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 11,
    lineHeight: 16,
  },
  attentionItemMeta: {
    marginTop: 5,
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 10,
    fontWeight: '800',
  },
});
