import {StyleSheet} from 'react-native';
import {getKolamTableVisualContract} from '../domain/kolam-table';
import {kolamVisualTokens as V} from '../domain/kolam-visual';
import {KOLAM_SALES_TABLE_VISUAL} from './kolam-sales-panel-visual';
import {KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL} from './kolam-settings-activity-table-visual';

const KOLAM_TABLE_VISUAL = getKolamTableVisualContract();

export const rowFrameStyles = StyleSheet.create({
  dataTableHeader: {
    minHeight: KOLAM_TABLE_VISUAL.body.rowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: KOLAM_TABLE_VISUAL.header.columnPaddingX,
    paddingVertical: KOLAM_TABLE_VISUAL.header.gutterY,
    backgroundColor: V.colors.tableHeader,
    borderTopColor: V.colors.border,
    borderTopWidth: 1,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  dataTable: {
    minHeight: KOLAM_TABLE_VISUAL.body.rowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: KOLAM_TABLE_VISUAL.body.cellPaddingX,
    paddingVertical: KOLAM_TABLE_VISUAL.body.gutterY,
    backgroundColor: V.colors.bg,
    borderBottomColor: V.colors.border,
    borderBottomWidth: KOLAM_TABLE_VISUAL.body.rowBorderBottom ? 1 : 0,
  },
  form: {
    minHeight: V.layout.tableRowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    borderTopColor: V.colors.border,
    borderTopWidth: 1,
  },
  endpoint: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  surface: {
    minHeight: V.layout.tableRowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    backgroundColor: V.colors.bg,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  selectable: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    borderTopColor: V.colors.border,
    borderTopWidth: 1,
  },
  cart: {
    minHeight: V.layout.tableRowMinHeight,
    paddingVertical: V.layout.tableCellPaddingY,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  pluginRegistry: {
    minHeight: 112,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    backgroundColor: V.colors.bg,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  sales: {
    minHeight: KOLAM_SALES_TABLE_VISUAL.body.rowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    backgroundColor: V.colors.bg,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  settingsActivityHeader: {
    minHeight: KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.body.rowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal:
      KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.header.columnPaddingX,
    paddingVertical: KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.header.gutterY,
    backgroundColor: V.colors.tableHeader,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  settingsActivity: {
    minHeight: KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.body.rowMinHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.body.cellPaddingX,
    paddingVertical: KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.body.gutterY,
    borderBottomColor: V.colors.border,
    borderBottomWidth:
      KOLAM_SETTINGS_ACTIVITY_TABLE_VISUAL.body.rowBorderBottom ? 1 : 0,
    backgroundColor: V.colors.bg,
  },
  settingsPermission: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingLeft: 36,
    paddingRight: 12,
    paddingVertical: 10,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  selectableSelected: {
    backgroundColor: V.colors.successSoft,
  },
});