import {listFrameStyles as styles} from './kolam-list-frame-styles';
import type {KolamListFrameVariant} from './kolam-list-frame-types';

export function getListFrameStyle(variant: KolamListFrameVariant) {
  switch (variant) {
    case 'pill':
      return styles.pill;
    case 'avatar':
      return styles.avatar;
    case 'metric':
      return styles.metric;
    case 'dashboardCount':
      return styles.dashboardCount;
    case 'dashboardMetric':
      return styles.dashboardMetric;
    case 'runtimeActionGrid':
      return styles.runtimeActionGrid;
    case 'runtimeIdentityGrid':
      return styles.runtimeIdentityGrid;
    case 'pluginSummaryGrid':
      return styles.pluginSummaryGrid;
    case 'statsCardStrip':
      return styles.statsCardStrip;
    case 'pendingOrdersGrid':
      return styles.pendingOrdersGrid;
    case 'catalogGrid':
      return styles.catalogGrid;
    case 'dashboardRail':
      return styles.dashboardRail;
    case 'dashboardRailAction':
      return styles.dashboardRailAction;
    case 'breadcrumbTrail':
      return styles.breadcrumbTrail;
    case 'pluginList':
      return styles.pluginList;
    case 'attentionList':
      return styles.attentionList;
    case 'attentionActions':
      return styles.attentionActions;
    case 'authControls':
      return styles.authControls;
    case 'authSourcePicker':
      return styles.authSourcePicker;
    case 'formGrid':
      return styles.formGrid;
    case 'operationalGrid':
      return styles.operationalGrid;
    case 'operationalStack':
      return styles.operationalStack;
    case 'commandList':
      return styles.commandList;
    case 'descriptionList':
      return styles.descriptionList;
    case 'endpointList':
      return styles.endpointList;
    case 'menuDockGroup':
      return styles.menuDockGroup;
    case 'cartActionRow':
      return styles.cartActionRow;
    case 'discountControlRow':
      return styles.discountControlRow;
    case 'saleActions':
      return styles.saleActions;
    case 'dashboardHeaderActions':
      return styles.dashboardHeaderActions;
    case 'dashboardVisitConfirmationsList':
      return styles.dashboardVisitConfirmationsList;
    case 'topNavLeft':
      return styles.topNavLeft;
    case 'topNavRight':
      return styles.topNavRight;
    case 'controlTabShell':
      return styles.controlTabShell;
    case 'filterBar':
      return styles.filterBar;
    case 'menuSectionActions':
      return styles.menuSectionActions;
    case 'pendingOrdersActionLink':
      return styles.pendingOrdersActionLink;
    case 'pendingOrdersBadges':
      return styles.pendingOrdersBadges;
    case 'pendingOrdersStatusBadges':
      return styles.pendingOrdersStatusBadges;
    case 'roleEditorActions':
      return styles.roleEditorActions;
    case 'roleEditorToolbar':
      return styles.roleEditorToolbar;
    case 'roleInfoActions':
      return styles.roleInfoActions;
    case 'sellableCatalogTabs':
      return styles.sellableCatalogTabs;
    case 'summaryBadges':
      return styles.summaryBadges;
    case 'surfacePanelTabs':
      return styles.surfacePanelTabs;
    case 'commandPaletteSearchRow':
      return styles.commandPaletteSearchRow;
    case 'dashboardStatChannelRows':
      return styles.dashboardStatChannelRows;
    case 'dashboardStatChannelGrid':
      return styles.dashboardStatChannelGrid;
    case 'wrap':
    default:
      return styles.wrap;
  }
}
