import {StyleSheet} from 'react-native';
import {getDashboardCustomerVisitConfirmationsVisualContract} from '../domain/dashboard-customer-visit-confirmations';
import {getDashboardCountVisualContract} from '../domain/dashboard-counts';
import {getDashboardHeaderVisualContract} from '../domain/dashboard-header';
import {getDashboardStatsVisualContract} from '../domain/dashboard-stats';
import {kolamVisualTokens as V} from '../domain/kolam-visual';
import {
  PENDING_ORDERS_VISUAL,
  pendingOrdersCardHeaderCompact,
} from './kolam-dashboard-pending-orders-visual';
import {
  DASHBOARD_RAIL_VISUAL,
  liveCardHeaderCompact as dashboardRailHeaderCompact,
} from './kolam-dashboard-rail-visual';
import {
  DASHBOARD_SALES_GRAPH_VISUAL,
  liveCardHeaderCompact as salesGraphHeaderCompact,
} from './kolam-dashboard-sales-graph-visual';

const DASHBOARD_HEADER_VISUAL = getDashboardHeaderVisualContract();
const DASHBOARD_COUNT_VISUAL = getDashboardCountVisualContract();
const DASHBOARD_STATS_VISUAL = getDashboardStatsVisualContract();
const VISIT_CONFIRMATIONS_VISUAL =
  getDashboardCustomerVisitConfirmationsVisualContract();

export const headerFrameStyles = StyleSheet.create({
  attentionPanel: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: V.layout.cardCompactSpacing,
    paddingVertical: 10,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  catalogCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  checkoutSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dashboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: DASHBOARD_HEADER_VISUAL.layout.alignItems,
    gap: DASHBOARD_HEADER_VISUAL.layout.gap,
    minHeight: DASHBOARD_HEADER_VISUAL.layout.minHeight,
    paddingTop: DASHBOARD_HEADER_VISUAL.layout.paddingTop,
    paddingBottom: DASHBOARD_HEADER_VISUAL.layout.paddingBottom,
    marginBottom: V.layout.cardSpacing,
  },
  dashboardCountSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: DASHBOARD_COUNT_VISUAL.section.headerGapX,
    marginBottom: 0,
    paddingHorizontal: DASHBOARD_COUNT_VISUAL.section.headerPaddingX,
    paddingTop: DASHBOARD_COUNT_VISUAL.section.headerPaddingTop,
    paddingBottom: DASHBOARD_COUNT_VISUAL.section.headerPaddingBottom,
    borderBottomColor: V.colors.border,
    borderBottomWidth: DASHBOARD_COUNT_VISUAL.section.headerBorderBottom ? 1 : 0,
  },
  dashboardVisitConfirmations: {
    paddingHorizontal: VISIT_CONFIRMATIONS_VISUAL.header.paddingX,
  },
  detailPanel: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: 11,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  pendingOrders: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: PENDING_ORDERS_VISUAL.header.gapY,
    marginBottom: 0,
    ...pendingOrdersCardHeaderCompact,
    paddingVertical: PENDING_ORDERS_VISUAL.header.paddingY,
    borderBottomColor: V.colors.border,
    borderBottomWidth: PENDING_ORDERS_VISUAL.header.borderBottom ? 1 : 0,
  },
  pendingOrdersTitleRow: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pendingOrdersMetaRow: {
    gap: 5,
  },
  dashboardRail: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 0,
    ...dashboardRailHeaderCompact,
    paddingVertical: DASHBOARD_RAIL_VISUAL.layout.headerPaddingY,
  },
  salesGraph: {
    minHeight: 44,
    flexDirection: 'row',
    flexWrap: DASHBOARD_SALES_GRAPH_VISUAL.header.flexWrap,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: DASHBOARD_SALES_GRAPH_VISUAL.header.gapY,
    marginBottom: 0,
    ...salesGraphHeaderCompact,
    paddingVertical: DASHBOARD_SALES_GRAPH_VISUAL.header.paddingY,
    borderBottomColor: V.colors.border,
    borderBottomWidth: DASHBOARD_SALES_GRAPH_VISUAL.header.borderBottom ? 1 : 0,
  },
  salesGraphSummaryColumn: {
    minWidth: DASHBOARD_SALES_GRAPH_VISUAL.header.summaryColumnMinWidth,
    maxWidth: DASHBOARD_SALES_GRAPH_VISUAL.header.summaryColumnMaxWidth,
    flexBasis: DASHBOARD_SALES_GRAPH_VISUAL.header.summaryColumnBasis,
    flexShrink: 1,
  },
  salesGraphTitleRow: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  salesGraphDescriptionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
  },
  metricCard: {
    minHeight: DASHBOARD_STATS_VISUAL.header.minHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: DASHBOARD_STATS_VISUAL.header.gapX,
  },
  menuSection: {
    minHeight: V.layout.navItemHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  menuTitle: {
    minHeight: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  moduleSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  paginationFooter: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: 11,
    borderTopColor: V.colors.border,
    borderTopWidth: 1,
    backgroundColor: V.colors.bg,
  },
  pluginSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  runtimeActionCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  runtimeIdentityStrip: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  runtimeIdentityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  settingsRoleEditorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  settingsRoleInfoPanel: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: 12,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
    backgroundColor: V.colors.muted,
  },
  settingsWebFormHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  statusPanel: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: V.layout.cardSpacing,
    paddingTop: V.layout.cardCompactSpacing,
    paddingBottom: 12,
    backgroundColor: V.colors.bg,
  },
  userMenuHeader: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: V.layout.cardCompactSpacing,
    paddingVertical: 12,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  statusPanelTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  surfacePanel: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: V.layout.tableCellPaddingY,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  syncActivityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  rolePermissionGroup: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: V.colors.secondary,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
});
