import {StyleSheet} from 'react-native';
import {kolamVisualTokens as V} from '../domain/kolam-visual';

export const detailPanelStyles = StyleSheet.create({
  panel: {
    marginHorizontal: V.layout.tableCellPaddingX,
    marginTop: 12,
    marginBottom: 4,
    overflow: 'hidden',
    borderRadius: V.radius.lg,
    borderColor: V.colors.border,
    borderWidth: 1,
    backgroundColor: V.colors.bg,
  },
  header: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: 11,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
  },
  title: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 14,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 3,
    maxWidth: 480,
    color: V.colors.mutedFg,
    fontFamily: 'Consolas',
    fontSize: 11,
  },
  closeButton: {
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: V.radius.lg,
    borderColor: V.colors.border,
    borderWidth: 1,
    backgroundColor: V.colors.bg,
  },
  closeText: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '900',
  },
  body: {
    gap: 10,
    paddingHorizontal: V.layout.tableCellPaddingX,
    paddingVertical: 13,
  },
  field: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  fieldLabel: {
    width: 112,
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  fieldValue: {
    flex: 1,
    minWidth: 0,
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  fieldValueMono: {
    fontFamily: 'Consolas',
    fontSize: 11,
  },
  warningBox: {
    gap: 6,
    padding: 12,
    borderRadius: V.radius.lg,
    borderColor: V.colors.warning,
    borderWidth: 1,
    backgroundColor: V.colors.warningSoft,
  },
  warningTitle: {
    color: V.colors.warning,
    fontFamily: V.fontFamily,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  warningFlag: {
    color: V.colors.warning,
    fontFamily: 'Consolas',
    fontSize: 11,
    fontWeight: '800',
  },
});
