import {StyleSheet} from 'react-native';
import {kolamVisualTokens as V} from '../domain/kolam-visual';

export const userMenuIconStyles = StyleSheet.create({
  dangerTint: {
    backgroundColor: V.colors.danger,
    borderColor: V.colors.danger,
  },
  dashboardIcon: {
    width: 15,
    height: 15,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
  },
  dashboardTile: {
    width: 6,
    height: 6,
    borderRadius: 2,
    backgroundColor: V.colors.fg,
  },
  settingsIcon: {
    width: 17,
    height: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsRing: {
    width: 11,
    height: 11,
    borderRadius: 6,
    borderColor: V.colors.fg,
    borderWidth: 2,
  },
  settingsToothVertical: {
    position: 'absolute',
    width: 3,
    height: 17,
    borderRadius: 999,
    backgroundColor: V.colors.fg,
  },
  settingsToothHorizontal: {
    position: 'absolute',
    width: 17,
    height: 3,
    borderRadius: 999,
    backgroundColor: V.colors.fg,
  },
  commandIcon: {
    width: 17,
    height: 17,
  },
  commandCorner: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 7,
    height: 7,
    borderRadius: 3,
    borderColor: V.colors.fg,
    borderWidth: 2,
  },
  commandCornerTopRight: {
    right: 0,
    left: undefined,
  },
  commandCornerBottomLeft: {
    bottom: 0,
    top: undefined,
  },
  commandCornerBottomRight: {
    right: 0,
    bottom: 0,
    left: undefined,
    top: undefined,
  },
  supportIcon: {
    width: 17,
    height: 17,
    alignItems: 'center',
  },
  supportRing: {
    width: 15,
    height: 15,
    borderRadius: 8,
    borderColor: V.colors.fg,
    borderWidth: 2,
  },
  supportLine: {
    position: 'absolute',
    top: 4,
    width: 5,
    height: 2,
    borderRadius: 999,
    backgroundColor: V.colors.fg,
    transform: [{rotate: '-25deg'}],
  },
  supportDot: {
    position: 'absolute',
    bottom: 3,
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: V.colors.fg,
  },
  logoutIcon: {
    width: 17,
    height: 17,
  },
  logoutDoor: {
    position: 'absolute',
    left: 1,
    top: 2,
    width: 8,
    height: 13,
    borderRadius: 2,
    borderColor: V.colors.fg,
    borderWidth: 2,
  },
  logoutArrow: {
    position: 'absolute',
    right: 1,
    top: 8,
    width: 10,
    height: 2,
    borderRadius: 999,
    backgroundColor: V.colors.fg,
  },
  logoutArrowHead: {
    position: 'absolute',
    right: 1,
    top: 5,
    width: 7,
    height: 7,
    borderRightColor: V.colors.fg,
    borderRightWidth: 2,
    borderTopColor: V.colors.fg,
    borderTopWidth: 2,
    transform: [{rotate: '45deg'}],
  },
});
