import {StyleSheet} from 'react-native';
import {kolamVisualTokens as V} from '../domain/kolam-visual';
import {
  KOLAM_AUTH_FORM_VISUAL,
  KOLAM_AUTH_INPUT_SHADOW,
} from './kolam-auth-panel-visual';

export const authPanelStyles = StyleSheet.create({
  authPanel: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
    marginTop: V.layout.cardSpacing,
    marginBottom: 14,
    padding: 14,
    borderRadius: V.radius.lg,
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderWidth: 1,
  },
  authPanelLogin: {
    width: '100%',
    marginTop: 0,
    marginBottom: 0,
    padding: 14,
    flexDirection: 'column',
    alignItems: 'stretch',
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderColor: 'rgba(255, 255, 255, 0.62)',
    borderRadius: 8,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 18},
    shadowOpacity: 0.18,
    shadowRadius: 36,
    elevation: 8,
  },
  authIdentity: {
    flex: 1,
  },
  authLabel: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  authUser: {
    marginTop: 4,
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 17,
    fontWeight: '900',
  },
  authMessage: {
    marginTop: 2,
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 13,
  },
  authMessageLogin: {
    marginTop: 2,
    color: V.colors.danger,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '700',
  },
  authAccess: {
    marginTop: 4,
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '900',
  },
  authSourceHint: {
    marginTop: 3,
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
  },
  authControls: {
    flex: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  authControlsLogin: {
    width: '100%',
    flex: 0,
    flexDirection: 'column',
    flexWrap: 'nowrap',
    gap: 10,
    alignItems: 'stretch',
  },
  authSourcePicker: {
    flexDirection: 'row',
    gap: 6,
  },
  authPasswordField: {
    position: 'relative',
    width: '100%',
    justifyContent: 'center',
  },
  authPasswordInputWithReveal: {
    paddingRight: 42,
  },
  authPasswordRevealButton: {
    position: 'absolute',
    right: 5,
    top: 3,
  },
  authModeTabs: {
    flexDirection: 'row',
    gap: 4,
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
    paddingBottom: 6,
  },
  authModeTab: {
    minHeight: 28,
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  authModeTabActive: {
    backgroundColor: V.colors.fg,
  },
  authModeTabText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  authModeTabTextActive: {
    color: V.colors.bg,
  },
  authOtpHintBox: {
    gap: 3,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: V.colors.muted,
    borderColor: V.colors.border,
    borderWidth: 1,
  },
  authOtpHintText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
  },
  authOtpBackButton: {
    alignSelf: 'flex-start',
    minHeight: 24,
    justifyContent: 'center',
  },
  authOtpBackText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  authInput: {
    flex: 1,
    minHeight: KOLAM_AUTH_FORM_VISUAL.input.height,
    minWidth: 170,
    paddingHorizontal: V.control.inputPaddingX,
    borderRadius: KOLAM_AUTH_FORM_VISUAL.input.radius,
    color: V.colors.fg,
    backgroundColor: V.colors.bg,
    borderColor: V.colors.input,
    borderWidth: 1,
    fontFamily: V.fontFamily,
    fontSize: KOLAM_AUTH_FORM_VISUAL.input.fontSize,
    ...KOLAM_AUTH_INPUT_SHADOW,
  },
  authInputLogin: {
    width: '100%',
    flex: 0,
    minWidth: 0,
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 6,
    color: V.colors.fg,
    backgroundColor: V.colors.bg,
    borderColor: V.colors.input,
    borderWidth: 1,
    fontFamily: V.fontFamily,
    fontSize: 12,
  },
  authInputWide: {
    flexGrow: 1,
    minWidth: 260,
    minHeight: KOLAM_AUTH_FORM_VISUAL.input.height,
    paddingHorizontal: V.control.inputPaddingX,
    borderRadius: KOLAM_AUTH_FORM_VISUAL.input.radius,
    color: V.colors.fg,
    backgroundColor: V.colors.bg,
    borderColor: V.colors.input,
    borderWidth: 1,
    fontFamily: V.fontFamily,
    fontSize: KOLAM_AUTH_FORM_VISUAL.input.fontSize,
    ...KOLAM_AUTH_INPUT_SHADOW,
  },
});
