/**
 * PO Copilot chrome — layout/spacing from DA-Dara-Plugin
 * `shipping-delivery.css` (shared with shipping); colors follow Kolam light theme.
 */
import { StyleSheet } from 'react-native';
import { kolamVisualTokens as V } from '../domain/kolam-visual';

export const poCopilotStyles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  shell: {
    flexDirection: 'column',
    gap: 16,
  },
  shellHeader: {
    alignItems: 'flex-start',
    borderBottomColor: V.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'space-between',
    paddingBottom: 14,
  },
  heading: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 26,
    marginTop: 3,
  },
  desc: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
    maxWidth: 760,
  },
  shellActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  body: {
    flexDirection: 'column',
    gap: 16,
  },
  deliveryPanel: {
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  deliveryPanelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  sideBySideGrid: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  sideBySideItem: {
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 320,
  },
  rangeTabs: {
    backgroundColor: V.colors.muted,
    borderColor: V.colors.border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 3,
    padding: 4,
  },
  rangeBtn: {
    backgroundColor: 'transparent',
    borderRadius: 7,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  rangeBtnActive: {
    backgroundColor: V.colors.bg,
  },
  rangeBtnText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    fontWeight: '600',
  },
  rangeBtnTextActive: {
    color: V.colors.fg,
  },
  sectionCard: {
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  botStrip: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  botStripHead: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  botStripActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  sectionTitle: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 15,
    fontWeight: '700',
    margin: 0,
  },
  sectionDesc: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    marginTop: 5,
  },
  notice: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
  },
  loadingText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    padding: 8,
  },
  notifyRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
    marginTop: 12,
  },
  notifyToggle: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  notifyLabel: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 14,
  },
  link: {
    color: V.colors.primary,
    fontFamily: V.fontFamily,
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  roomRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  roomSelect: {
    flexBasis: 256,
    flexGrow: 1,
    maxWidth: 448,
    minWidth: 224,
  },
  healthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  healthRow: {
    backgroundColor: V.colors.muted,
    borderColor: V.colors.border,
    borderRadius: 10,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 160,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  healthOk: {
    backgroundColor: V.colors.successSoft,
    borderColor: V.colors.success,
  },
  healthBad: {
    backgroundColor: V.colors.dangerSoft,
    borderColor: V.colors.danger,
  },
  healthPlatform: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  healthState: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    marginTop: 4,
  },
  warnText: {
    color: V.colors.warning,
    fontFamily: V.fontFamily,
    fontSize: 12,
    marginTop: 8,
  },
  dangerText: {
    color: V.colors.danger,
    fontFamily: V.fontFamily,
    fontSize: 12,
    marginTop: 8,
  },
  botAvatar: {
    borderRadius: 999,
    flexShrink: 0,
    height: 56,
    width: 56,
  },
  botAvatarPh: {
    alignItems: 'center',
    backgroundColor: V.colors.muted,
    borderColor: V.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  botAvatarPhText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '700',
  },
  botUpload: {
    alignItems: 'center',
    backgroundColor: V.colors.muted,
    borderColor: V.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  botUploadText: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    fontWeight: '600',
  },
  botNameField: {
    flexBasis: 192,
    flexGrow: 1,
    gap: 4,
    maxWidth: 320,
    minWidth: 160,
  },
  botNameLabel: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '600',
  },
  botNameInput: {
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 13,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  kpiCard: {
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexBasis: '48%',
    flexDirection: 'column',
    flexGrow: 1,
    minHeight: 146,
    minWidth: 260,
    overflow: 'hidden',
  },
  kpiTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 14,
  },
  kpiLabel: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    marginBottom: 4,
  },
  kpiValue: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 22,
  },
  kpiTrend: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
  },
  kpiChart: {
    backgroundColor: V.colors.muted,
    borderRadius: 8,
    height: 42,
    marginBottom: 10,
    marginHorizontal: 12,
    overflow: 'hidden',
  },
  breakdown: {
    borderTopColor: V.colors.border,
    borderTopWidth: 1,
    marginTop: 'auto',
    paddingBottom: 12,
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  breakdownTitle: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    marginBottom: 10,
  },
  breakdownGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  breakdownItem: {
    alignItems: 'center',
    backgroundColor: V.colors.muted,
    borderRadius: 8,
    flex: 1,
    paddingHorizontal: 4,
    paddingVertical: 6,
  },
  breakdownName: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 11,
  },
  breakdownCount: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 2,
  },
  channelLogo: {
    height: 28,
    marginBottom: 4,
    resizeMode: 'contain',
    width: 28,
  },
  meta: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
  },
  opsBlock: {
    gap: 8,
  },
  opsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  opsCard: {
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 260,
    overflow: 'hidden',
  },
  opsCardTitle: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  opsPanel: {
    maxHeight: 256,
    padding: 8,
  },
  opsEmpty: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  opsItem: {
    backgroundColor: V.colors.muted,
    borderColor: V.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 2,
    marginBottom: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  opsTime: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 11,
  },
  opsInvoice: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 11,
    fontWeight: '600',
  },
  opsDetail: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    marginTop: 2,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  badge: {
    backgroundColor: V.colors.bg,
    borderColor: V.colors.border,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeText: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 10,
  },
  procurementBox: {
    backgroundColor: V.colors.mutedSoft,
    borderColor: V.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  procurementHead: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  procurementTitle: {
    color: V.colors.fg,
    fontFamily: V.fontFamily,
    fontSize: 12,
    fontWeight: '600',
  },
  procurementNote: {
    color: V.colors.mutedFg,
    fontFamily: V.fontFamily,
    fontSize: 10,
    marginTop: 8,
  },
});
