const fs = require('fs');
const path = require('path');

const componentsDir = path.join(__dirname, '..', 'src', 'components');
const copyStackComponents = [
  'kolam-dashboard-sales-graph-header.tsx',
  'kolam-action-button.tsx',
  'kolam-badge.tsx',
  'kolam-breadcrumb-item.tsx',
  'kolam-button.tsx',
  'kolam-control-tab-item.tsx',
  'kolam-menu-item-row.tsx',
  'kolam-menu-section-toggle.tsx',
  'kolam-pagination-item.tsx',
  'kolam-segment.tsx',
  'kolam-select-trigger.tsx',
  'kolam-sidebar-brand-wordmark.tsx',
  'kolam-sidebar-nav-group.tsx',
  'kolam-surface-contract-list.tsx',
  'kolam-text-action-label.tsx',
  'kolam-attention-header-action.tsx',
  'kolam-attention-item-copy.tsx',
  'kolam-attention-item-title-row.tsx',
  'kolam-attention-panel-title-block.tsx',
  'kolam-auth-identity.tsx',
  'kolam-avatar-pill-empty.tsx',
  'kolam-avatar-pill.tsx',
  'kolam-breadcrumb-trail.tsx',
  'kolam-cart-row-discount-label.tsx',
  'kolam-cart-row-item-info.tsx',
  'kolam-checkout-summary-header.tsx',
  'kolam-command-palette-item-copy.tsx',
  'kolam-command-palette-item-meta.tsx',
  'kolam-command-palette-section-block.tsx',
  'kolam-dashboard-header-copy.tsx',
  'kolam-dashboard-pending-orders-header.tsx',
  'kolam-dashboard-pending-orders-meta-row.tsx',
  'kolam-dashboard-pending-orders-range-card.tsx',
  'kolam-dashboard-pending-orders-title-row.tsx',
  'kolam-dashboard-rail-empty-state.tsx',
  'kolam-dashboard-rail-header.tsx',
  'kolam-dashboard-rail-row.tsx',
  'kolam-dashboard-sales-graph-empty-state.tsx',
  'kolam-dashboard-session-pill.tsx',
  'kolam-dashboard-stat-channel-row.tsx',
  'kolam-dashboard-stat-header-copy.tsx',
  'kolam-data-table-header-cell.tsx',
  'kolam-data-table-primary-cell.tsx',
  'kolam-data-table-text-cell.tsx',
  'kolam-description-list-details.tsx',
  'kolam-description-list-term.tsx',
  'kolam-detail-panel-field-row.tsx',
  'kolam-detail-panel-header.tsx',
  'kolam-endpoint-list-contract.tsx',
  'kolam-filter-search-control.tsx',
  'kolam-menu-count-badge.tsx',
  'kolam-menu-title.tsx',
  'kolam-menu-item-group-label.tsx',
  'kolam-metric-card-header.tsx',
  'kolam-metric-card-value.tsx',
  'kolam-nav-item-badge.tsx',
  'kolam-nav-item-copy.tsx',
  'kolam-notification-badge.tsx',
  'kolam-pagination-summary.tsx',
  'kolam-info-list-copy.tsx',
  'kolam-info-list-meta.tsx',
  'kolam-empty-state.tsx',
  'kolam-module-panel.tsx',
  'kolam-native-form-section.tsx',
  'kolam-operational-empty.tsx',
  'kolam-plugin-registry-row-capabilities.tsx',
  'kolam-plugin-registry-table-header.tsx',
  'kolam-plugin-summary-card-label.tsx',
  'kolam-plugin-summary-card-value.tsx',
  'kolam-plugin-registry-row-identity.tsx',
  'kolam-plugin-registry-row-repo-route.tsx',
  'kolam-plugin-registry-row-status.tsx',
  'kolam-readiness-copy.tsx',
  'kolam-quantity-stepper-value.tsx',
  'kolam-quick-search-shortcut.tsx',
  'kolam-runtime-action-card-copy.tsx',
  'kolam-runtime-action-card-header.tsx',
  'kolam-runtime-identity-card-header.tsx',
  'kolam-runtime-identity-client-pill.tsx',
  'kolam-runtime-identity-status-badge.tsx',
  'kolam-runtime-identity-card.tsx',
  'kolam-runtime-identity-header.tsx',
  'kolam-sales-panel-header.tsx',
  'kolam-search-field-trailing-label.tsx',
  'kolam-sellable-catalog-header.tsx',
  'kolam-settings-activity-duration-cell.tsx',
  'kolam-settings-activity-ip-cell.tsx',
  'kolam-settings-activity-path-cell.tsx',
  'kolam-settings-activity-time-cell.tsx',
  'kolam-settings-activity-user-cell.tsx',
  'kolam-settings-role-editor-title-copy.tsx',
  'kolam-settings-role-info-copy.tsx',
  'kolam-settings-role-info-notice.tsx',
  'kolam-settings-role-permission-group-header.tsx',
  'kolam-settings-role-permission-resource.tsx',
  'kolam-settings-role-table-header.tsx',
  'kolam-settings-role-member-preview.tsx',
  'kolam-settings-role-permission-count-pill.tsx',
  'kolam-settings-activity-table-header-cell.tsx',
  'kolam-settings-web-field-label.tsx',
  'kolam-settings-web-value-field.tsx',
  'kolam-settings-web-switch-field.tsx',
  'kolam-summary-block-title.tsx',
  'kolam-summary-card-badges.tsx',
  'kolam-summary-card-list-item.tsx',
  'kolam-summary-empty.tsx',
  'kolam-summary-line.tsx',
  'kolam-sync-activity-item-header.tsx',
  'kolam-sync-status-bar.tsx',
  'kolam-top-navigation-avatar.tsx',
  'kolam-total-row-text.tsx',
  'kolam-unified-source-panel.tsx',
  'kolam-user-menu-avatar.tsx',
  'kolam-user-menu-item.tsx',
  'kolam-workflow-notice-row.tsx',
  'kolam-plugin-registry-route-preview.tsx',  'kolam-settings-web-form-header.tsx',
  'kolam-settings-web-form-section-header.tsx',
  'kolam-stats-card.tsx',
  'kolam-status-panel-meta.tsx',
  'kolam-status-panel-title-row.tsx',
  'kolam-surface-panel-copy.tsx',
  'kolam-sync-activity-item.tsx',
  'kolam-unified-runtime-footer.tsx',
  'kolam-user-menu-profile.tsx',
  'kolam-attention-tone-badge.tsx',
  'kolam-cart-row-actions.tsx',
  'kolam-checkout-shipping-field.tsx',
  'kolam-checkout-discount-row.tsx',
  'kolam-cashflow-close-preview.tsx',
  'kolam-catalog-card.tsx',
  'kolam-dashboard-count-card.tsx',
  'kolam-dashboard-pending-orders-action-link.tsx',
  'kolam-dashboard-rail-action.tsx',
  'kolam-dashboard-rail-value-badge.tsx',
  'kolam-dashboard-sales-graph-point.tsx',
  'kolam-detail-panel-warning-box.tsx',
  'kolam-sale-row.tsx',
  'kolam-menu-dock-widgets.tsx',
  'kolam-quick-search-identity.tsx',
  'kolam-selector-chip-label.tsx',
  'kolam-state-pill.tsx',
  'kolam-status-badge-label.tsx',
  'kolam-quantity-stepper-button.tsx',];

describe('KolamCopyStack usage', () => {
  it('keeps linear title and description copy on the shared copy stack', () => {
    const regressions = copyStackComponents
      .map(file => {
        const source = fs.readFileSync(path.join(componentsDir, file), 'utf8');

        const reactNativeImport = source.match(
          /import\s+\{([^}]*)\}\s+from ['"]react-native['"]/,
        );
        const directTextImport = reactNativeImport
          ? reactNativeImport[1].split(',').some(part => part.trim() === 'Text')
          : false;

        return {
          file,
          hasCopyStack:
            source.includes("from './kolam-copy-stack'") ||
            source.includes("from './kolam-empty-state'"),
          directTextImport,
        };
      })
      .filter(result => !result.hasCopyStack || result.directTextImport);

    expect(regressions).toEqual([]);
  });
});
